- name: Transferir Películas
  hosts: http://192.168.100.193/#/
  become: true  # Ejecutar comandos como sudo

  tasks:
    - name: Mover archivos de la carpeta de descargas a la carpeta de películas
      command: mv /Root/DATA/Downloads/complete/*.mkv /Root/DATA/Media/movies/
      args:
        chdir: /Root/DATA/Downloads/
      become_user: Tuna
      become_method: sudo
      become_flags: '-H -S -n'
   
