---
- name: Transferir Películas
  hosts: 192.168.100.193
  become: true  # Ejecutar comandos como sudo

  tasks:
    - name: Mover archivos de la carpeta de descargas a la carpeta de películas
      command: mv /Root/DATA/Downloads/complete/*.mkv /Root/DATA/Media/movies/
      args:

 become_user: tu_usuario
 become_method: sudo
 become_flags: '-H -S -n'
 gather_facts: false
